name: Bauen und auf Server hochladen

on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Node.js
                uses: actions/setup-node@v1
                with:
                    node-version: '15.x'
            -   name: Abhängigkeiten installieren
                run: npm ci
            -   name: Bauen
                run: npm run build --if-present

            -   name: Hochladen
                uses: hrsetyono/git-sftp-action@v4
                with:
                    url: ${{ secrets.URL }}
                    user: ${{ secrets.USER }}
                    password: ${{ secrets.PASSWORD }}
                    syncroot: './dist'
